name : Github Actions 실행시켜보기

on : 
  push : 
    branch : 
      - main

jobs : 
  My-Depoly-Job : 
    runs-on : ubuntu-latest

    steps : 
      - name : Hello World 출력하기
        run : echo "Hello World"

      - name : 여러 명령어 문장 작성하기
        run : |
          echo "Good"
          echo "Morning"
          pwd
      
      - name : 변수 사용하기
        run : |
          echo $GITHUB_REPOSITORY
          echo $GITHUB_SHA